### ISSUE TITLE
CSRFHandler

### ISSUE THREAD

**Issue by pcholder** [eclipse-vertx/vertx-auth#130]
### Context

CSRFHandler generates token from local variable **salt + current time** on each GET request (and some others, besides POST) and protects POSTs. Even the token is stored in cookies, this handler successfully validates any token from any alive session. 
Consequently:
1. if pair SessionA + tokenA is valid then SessionB + tokenA is also valid

2. I can not use some csrf-protected "/api/*" which supports only POST requests until any GET request under CSRFHandler. I'm sure it can be more friendly.

**Comment by pmlopes** [comment]
The reason the handler validates any session is because it is stateless, the state is preserved in the session cookie, if the cookie is hijacked this could be because there are some security issues such as not using `HTTPS`. You can make it even more secure by enforcing a Same Origin Policy [1].

Regarding item 2 it is expected behavior, you must first make a request to get a token and then you can use it in the next call, this is how the Cross Site Request Forgery protection works [2].

[1] https://en.wikipedia.org/wiki/Same-origin_policy
[2] https://en.wikipedia.org/wiki/Cross-site_request_forgery

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-web #587](https://github.com/vert-x3/vertx-web/issues/587) via [**ZenHub**](https://www.zenhub.com/)
