### ISSUE TITLE
Read-me file to compile and run

### ISSUE THREAD

**Issue by ajayv14** [eclipse-vertx/vertx-auth#145]
Hi, a readme file with exact steps to run these example would be great, thanks

**Comment by pmlopes** [comment]
@ajayv14 all examples live here: https://github.com/vert-x3/vertx-examples

Since this module is quite low level you will be it's usage with other modules like:

https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/auth
https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/jwt

And of course in the documentation section:

http://vertx.io/docs/#authentication_and_authorisation

**Comment by ajayv14** [comment]
Thanks for the reply..:), will read thro the links, thank you.
