### ISSUE TITLE
Regression in Rx-ification

### ISSUE THREAD

**Issue by jponge** [eclipse-vertx/vertx-auth#155]
### Version

* vert.x core: 3.5.0.Beta1
* vert.x auth: 3.5.0.Beta1

### Context

Upgrading the `vert-x3/vertx-guide-for-java-devs` project to 3.5.0.Beta1, I got a compilation error in the `step-8` module (the one that introduces RxJava support).

I haven't attempted migrating to RxJava2 yet, but there is a regression in the RxJava code generation support:

https://github.com/vert-x3/vertx-guide-for-java-devs/blob/wip/3.5.0-upgrade/step-8/src/main/java/io/vertx/guides/wiki/http/HttpServerVerticle.java#L131

This used to compile with the Rx-ification also bringing a delegate method with `JsonObject` support, which is not the case anymore.

Looking into the generated code only the version with `JWTAuthOptions` is present:

```java
public static JWTAuth create(Vertx vertx, JWTAuthOptions config) { 
    JWTAuth ret = JWTAuth.newInstance(io.vertx.ext.auth.jwt.JWTAuth.create(vertx.getDelegate(), config));
    return ret;
  }
```

### Do you have a reproducer?

https://github.com/vert-x3/vertx-guide-for-java-devs/tree/wip/3.5.0-upgrade

### Steps to reproduce

`mvn clean package`

### Extra

Ping codegen wizard @vietj 😉

**Comment by pmlopes** [comment]
The issue has been fixed at the guide repo. The old API was not typed and not documented, now it is typed and documented, however since we introduced a DataObject where JsonObject was present we can only keep the original API for the Java side not the codegen side. If you're using a codegen layer you either need to go deep and get the delegate or update the code.

**Comment by jponge** [comment]
Thanks @pmlopes you rock 👍
