### ISSUE TITLE
Refactor roles/permissions to authorities

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#16]
Currently we have `user.hasRole(String)` and `user.hasPermission(String)` even though the separation of `roles` and `permissions` sounds logic there are some deficiencies with the current implementation.

The first false assumption is that roles and permissions are independent and relate to a user. So say that user `Paulo` has role `dev` and permission `push`. Now lets assume the whole application knows about the roles `dev` and `devops` and a `dev` role can `push` code and a `devops` role can `push` releases into production.

Now with our model if we want to assert if `Paulo` can `push` to production we need to do:

```
paulo.hasRole("devops") && paulo.hasPermission("push")
```

The logic here would fail since `false` && `true` is `false`. Now just say that because I am the lead developer i might have `read` access to prod to pull logs or something... so now `Paulo` is a `dev` with `push` permissions and `devops` with `read` permissions.

The same check from above will assert `true` even tough it is not correct. The `hasPermission` has no context about from which `role` to check the permission for.

How can we fix this:

We need to refactor the `User` to have a method `hasAuthority(String)` if we like the Spring style or `isPermitted(String)` if we like the Shiro style. After reading both I am tending for Shiro...

Now the assertion is a String, both Spring and Shiro have conventions about the format of the Strings. Looking at Shiro a authority has the format:

```
<role or domain>[:<action>[:<instance>]]
```

examples would be:

```
printers:print:color_printer_1st_floor
devops:read
dev:push
```

The impact is that using this approach we can have the same model fitting all current implementations:
- shiro
- jwt
- jdbc

The Strings are opaque so they only have specific meaning to the implementations and no assumptions on the format is made by `vertx-auth`, the usage of the format above is just an example and if one prefers can use String notation:

```
Role_devops
Role_dev
devops:push
devops:read
dev:push
```

Since the assumption is that the String are opaque it is to the implementation of `auth` providers to define if they support or not wildcards, e.g.: `printers:print:*`.

**Comment by stephanebastian** [comment]
Hey Paulo,
At the end of the day, an AuthProvider will read roles and permissions from a DB, an LDAP server, etc..
Roles and Permissions may be structured as above (domain:action:instance), support wildcards or not. 
The real issue here is to provide the _correct_ implementation for hasPermission() and hasRole() => Do we need to support wildcards, do we need to support domain:action:instance, etc. ? 
The thing is that we don't know in advance because this is something that is application specific. 
So since we do not know, I see two solutions here:
- Introduce a new interface so that the developer can configure the AuthProvider with the 'matcher' he needs to use

```
RoleAndPermissionMatcher (pick a better name ;) {
   boolean matchRoles(String role1, String role2);
   boolean matchPermissions(String perm1, String perm2);
}
```
- Remove the methods hasRole(), hasPermissions() and rather add 2 methods returning roles/ permissions (getRoles(), getPermissions())
  This way the AuthProvider is completely independent on how roles / permissions are structured and it's it up to the developper to do the right thing when checking permissions.

```
User {
   Collection<String> getRoles();
   Collection<String> getPermissions();
}
```

A dev would do:
user.getPermissions().contains("read"); // for strict equality

or 
Permissions.match(user.getPermissions(), "users:*"); // for something supporting wildcard

I personally have a preference for solution 1 because it makes my life easier but solution 2 would do.
what do you think?

**Comment by pmlopes** [comment]
Hi Stephane,

I'm currently updating the docs to make things explicit. So What you are suggesting for item 2 is similar to what we currently have. A user has a set of Roles and a set of Permissions. We are explicitly stating that roles and permissions are opaque Strings, that have no meaning to the auth module but do have meaning for the provider implementation.

Meaning that currently we match using String equality, however with shiro we could use Wildcard matching. I think that in order to allow this with the minimum change of API we could define a config boolean option to the Shiro Provider to match using wildcard.

Also note that only permissions should be matched with wildcards, not roles. A role is just a logical named collection of permissions.

**Comment by stephanebastian** [comment]
Paulo,
IMO a developer should be able to do wildcard matching even though he is not using a provider based on Shiro (for instance the new JDBC AuthProvider), don't you think?
The idea of matching using wildcards comes from Shiro (AFAIK) but it is so convenient that this could(/should?) be the default way of matching permissions in Vertx Auth (even for not Shiro Auth), WDYT?

**Comment by purplefox** [comment]
I'm confused - I thought we were getting rid of hasPermission()/hasRole() and replacing with isPermitted(), where the semantics of isPermitted() is completely up to the implementation?

**Comment by purplefox** [comment]
We can't mandate that a provider supports wildcard matching - many will not do this, and we can't do it ourselves as it's not possible in the general case to load all permisions/roles.

**Comment by purplefox** [comment]
Paulo - can you clarify whether we are getting rid of hasPermission()/hasRole() or not?

**Comment by pmlopes** [comment]
I've been updating the documentation to make all things clear:
- roles are named collections of permissions
- permissions are opaque strings
- wildcard support is a implementation detail and invisible to the API

Now in regards to the API we do have I haven't changed yet. I am doing the refactor, but i opened the PR too early.

So the plan is:

Now that the documentation is clear i will refactor:
- `hasPermission(String)` to `isPermitted(String)`
- `hasPermissions(Set<String>)` to `isPermitted(Set<String>)`

As we wrote on IRC yesterday I will keep the `hasRole` since it makes sense for most users. Now the implementations however can like with Shiro have its own way of defining roles or for other implementations it can use a pattern to filter them from the permissions.

**Comment by purplefox** [comment]
The bit I don't quite understand is why are we keeping hasRole?

It's my understanding that with the new isPermitted there is no requirement for a role/permission based model any more, and having hasRole seems to mandate that model...

**Comment by stephanebastian** [comment]
Guys, here are my 2 cents:

If you want to get to the barebone API for Auth but keep your options open to add more stuff later-on (post 3.0) based on user's requirements, I would suggest to only keep isPermitted(String) and get rid of hasRole().
I would even go one step further and IMO for 3.0 you don't even need the plural form isPermitted(Set<String>). 
When checking multiple permissions, some users would expect a logical OR and some others a logical AND. Since isPermitted(Set<String>) can't do both, we are better of providing a single method User.isPermitted(String) that people can use however they want:

```
if (user.isPermitted("permission1") || user.isPermitted("permission2") {

}
...
if (user.isPermitted("permission4") && user.isPermitted("permission5") {

}

```

An added benefit is that developers looking at the code immediately understand that if it is an OR or AND

**Comment by pmlopes** [comment]
the hasRole is indeed accessory method, my concern to keep it for now was to keep the Shiro API working on its full extent. However it will just cause noise for providers that do not support that model.

One can indeed live without it e.g.:
- JWT using the concept of claims is modeled with isPermitted
- DB can be anything, however the simplest schema can be modeled with isPermitted
- OAuth2 has the idea of scopes, which are plain Strings, again just modeled with isPermitted
- Shiro uses both Permissions and Roles, permissions is modeled with isPermited but Roles needs hasRole
- Spring security has GrantedAuthorities which is modeled with isPermitted

So it is not wise to keep hasRoles just for Shiro.

And I like the idea of Stephane to keep just one isPermitted because then we can handle both "and" and "or" of permissions.

**Comment by stephanebastian** [comment]
Paulo: Great, with one method, the Auth API is KISS ;)
Side question just to make sure that I understand things correctly regarding Shiro. 
Shiro used to be the only underlying lib to do Auth (LDAP, JDBC). Now JDBC is non blocking and not using Shiro. The only provider leveraging Shiro is the LDAP provider right?
Some time down the line, someone will surely refactor the LDAP provider and make it non blocking as well, right?
When this happens, Shiro will be not be needed anymore. Is this correct? Do you foresee providers in the future that will have to leverage Shiro, or Spring security ? Because I do not ...

**Comment by purplefox** [comment]
The Shiro impl contains a simple properties provider which is useful for small self contained apps.

Also you can plug in any other Shiro Realm that you have.

**Comment by purplefox** [comment]
The main purpose of the ShiroAuthProvider is so users can reuse their existing Shiro realm implementations.

**Comment by stephanebastian** [comment]
Got it. Thx

**Comment by mavencode01** [comment]
@pmlopes I'm trying to follow this thread but it appears I can't find the documentation describing what you last said. 
What am looking for is being able to specify both `permission` and `role` using jwt for a protected route and authorizing user that either has that permission or belong to the role.

http://vertx.io/docs/vertx-web/java/#_configuring_required_authorities

**Comment by pmlopes** [comment]
@mavencode01 with `vertx-auth` we use a simple model, which is `authorities`. IMO `permission` and `role` are more or less `micro` and `macro` `authorities`. So they do not differ much (their only difference is the meaning you give to it).

We standardized on using a simple string with an options separator `:` for systems that can do support the distinction between `role` and `permission`.

For JWT the spec is loose and says that any key in the token is a claim (except a few names under the registry) So when doing `isAuthorised(string)` we're looking into a json key for the given string.

For Shiro we split on the separator and look on permission and role.

For OAuth2 it depends on the backend, for `Keycloak` we split on the separator to look into either the `realm` or into the `resource` roles list.

For JDBC and Mongo it is a plain lookup on a table. but can be extended if the DDL is updated and the queries too.

But I must agree that this needs better documentation.

**Comment by mavencode01** [comment]
@pmlopes thanks for the clarification now
