### ISSUE TITLE
Add possibility to pass KeyStore object to JWTAuth.create

### ISSUE THREAD

**Issue by geromueller** [eclipse-vertx/vertx-auth#164]
### Version

* vert.x core: 3.4.2
* vert.x auth: 3.4.2

### Context

Add possibility to pass KeyStore object to JWTAuth.create. This would allow UnitTests without a keystore on disk.

**Comment by pmlopes** [comment]
@geromueller I'm in the process of deprecating all keystore code as it seems to be a major pain for users. The proposal is to upgrade either to use PEM files (OpenSSL) or JWK.

For PEM files you can review this: #191
For JWKs you can generate then using this webapp: https://mkjwk.org/

There is already code to work with JWK it's only missing the direct access from the JWT Auth create. The goal with these 2 approaches is that most providers e.g.: Google, Keycloak, etc... use JWKs and others provide public keys in PEM format while no provider seems to use keystores.

Also keystores make too many assumptions on key names, alias and certificates in order to get the right algorithm and keys.

**Comment by aschrijver** [comment]
Hi @pmlopes 

For which Vert.x version is this keystore deprecation planned (and the new implementation ready, incl. docs, tests)?

PS The site https://mkjwk.org/ has certificate errors.

**Comment by pmlopes** [comment]
@aschrijver the jwk code is in, so as of 3.6 the old keystore code will be deprecated. We have this rule that deprecated code is available for at least 3 releases under the same major release version.

**Comment by aschrijver** [comment]
Ok, thank you. That is great!

**Comment by pmlopes** [comment]
A command line alternative to mkjwk site can be found here: https://connect2id.com/products/nimbus-jose-jwt/generator

**Comment by pmlopes** [comment]
Docs updated:

https://github.com/vert-x3/vertx-auth/commit/3d4eed4e1fa952b98887ab89e3b31e4ae8ed40f8
https://github.com/vert-x3/vertx-auth/commit/314aa2cd4ba7a09eae2d4f2622f3dc7f06742660
