### ISSUE TITLE
Unify the hashing strategies following best practices and allow effortless migrations

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#180]
Currently both `JDBC` and `Mongo` hashing strategies are not compatible and are hard to upgrade. They do not have a simple API for hashing upgrades and this can be problematic for some projects.

This is a follow up from #179

The goals for this feature would be:

* [x] use the PHC string format?
* [x] allow plug of strong algorithms not bundled with the JDK (e.g.: bcrypt)
* [x] reusable between `JDBC` and `Mongo` or other

I'd like to get all feedback from @sonOfRa and @yawkat

**Comment by sonOfRa** [comment]
Well, considering this is a general problem, I've started to write a library to remedy this. If you like it, you can either add it as a dependency, or integrate the code directly into the vert.x codebase if so desired. It lives at https://github.com/sonOfRa/pwhash and is obviously still very incomplete since I only started writing any code on it today. However, some unpolished implementation for the general HashStrategy interface, and an implementation using argon2 are already present, so you can take a look at what I personally think would be a good API for this. I've spoken to @yawkat on IRC, and he seems to agree that the API looks good.

Currently, the API only handles hashing upgrades *within* a single algorithm, but I'm currently thinking about an API layout that would also allow switching between algorithms easily.

The library will come with at least bcrypt and argon2 in the end, but will also be extensible so that library users can add their own algorithms/formats depending on their needs.

Note: I've currently not added a license yet, but it'll end up being something like MIT/Apache or a dual license, so something that should be usable by vertx and other software easily.

**Comment by pmlopes** [comment]
I believe we could use the basic interfaces + simple implementation in vert.x and use a service loader to load external algorithms.

**Comment by pmlopes** [comment]
For reference hash strings should be stored according to: https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md

**Comment by sonOfRa** [comment]
Yes, that is basically how they are stored in the API I linked. The only problem is that that spec is out of date, and the authoritative source for the format is now the argon2 source code, see https://github.com/P-H-C/phc-string-format/issues/1 and https://github.com/P-H-C/phc-winner-argon2/issues/157

The format is somewhat ill-defined, but *mostly* well defined. Bcrypt for example works *almost* like the format, except it doesn't split up the salt and the hash with $, and that its sole parameter is not named, but just an integer. Otherwise I completely agree that we should adhere to this format.

**Comment by sonOfRa** [comment]
I've added another class to the library, the [MigrationStrategy](https://github.com/sonOfRa/pwhash/blob/master/src/main/java/de/slevermann/pwhash/MigrationStrategy.java).

While in the general case, an implementation of a HashStrategy only knows about *its own* specifics for needsRehash(), the MigrationStrategy knows about two strategies, namely the "to" and "from" strategies.

This would allow for example embedding vertx' current password hashing style into a HashStrategy of this kind, and then instantiate a 
```java
MigrationStrategy(vertxStrategy, bcryptStrategy)
```
and maybe later a
```java
MigrationStrategy(bcryptStrategy, argon2Strategy)
```

Note that this also allows chaining, since MigrationStrategy is also a HashStrategy. So if you have a database that is partially upgraded from a *very* old hash, like vertx to bcrypt, and you have mixed hashes of both, you can instantiate a

```java
MigrationStrategy(MigrationStrategy(vertxStrategy, bcryptStrategy), argon2Strategy)
```

I'm not quite sure yet if this is the API design I want, but I think it's a relatively good idea to allow seamless transitions.

**Comment by pmlopes** [comment]
@sonOfRa I was thinking something more on these lines:

https://github.com/vert-x3/vertx-auth/pull/182/commits/9c1d1160051c403f689d56736c20561267d2026b#diff-7a1027d749d98e558dd0699b9e019bbc

The idea is that anyone can add any extra algorithms they like by creating a simple jar file with a implementation of the interface:

https://github.com/vert-x3/vertx-auth/pull/182/commits/9c1d1160051c403f689d56736c20561267d2026b#diff-353c8da163b78e3d634d0f9f478cb6b6

And adding a service loader metadata file:

https://github.com/vert-x3/vertx-auth/pull/182/commits/9c1d1160051c403f689d56736c20561267d2026b#diff-9494b3d3b669a5515e2417b5221504af

Using this approach any algorithm weak or strong can be added.
