### ISSUE TITLE
AccessToken logout doesn't work

### ISSUE THREAD

**Issue by RaiBnod** [eclipse-vertx/vertx-auth#219]
### Version: 

* vert.x core: 3.5.1
* vert.x auth: 3.5.1

### Context and Issue
I am using Keycloak as the third-party authentication system. And It is very fine with the login but while I need to logout the session I face a problem. Detail code is written below:

        router.route("/api/logout").handler(ctx -> {
            User user = ctx.user();
            if (user != null) {
                AccessToken token = (AccessToken) user;
                token.logout(res -> {
                    if (res.succeeded()) {
                        System.out.println("I am succeeded: " + res);
                        ctx.response().setStatusCode(204).end();
                    } else {
                        System.out.println("Got failed: " + res);
                        ctx.fail(503);
                    }
                });
            } else {
                System.out.println("User is not logged in");
                ctx.fail(400);
            }
        });

On the above program, execution **AccessToken token** contains no any refresh_token, and results following error logs on signout:

**Got failed: Future{cause=Bad Request: {"error":"invalid_grant","error_description":"Invalid refresh token"}}**

How should I handle this issue?

**Comment by RaiBnod** [comment]
form.put("refresh_token", token.getString("refresh_token"));

This line of code on function '**public OAuth2TokenImpl logout(Handler<AsyncResult<Void>> callback)**' will get failed since context user doesn't give us the refresh_token value. Maybe, it should get refresh_token from the body.

**Comment by pmlopes** [comment]
That should only be added to the form if the value is not null or empty string

**Comment by RaiBnod** [comment]
I haven't found any option to access AccessToken with refresh_token, code is like this:

    private OAuth2Auth loginAuth;
    loginAuth.introspectToken(access_token,res->{
        if(res.succeeded()){
            System.out.println("Auth Success");
            AccessToken token=res.result();
            ctx.setUser(token);
            ctx.next();
        }else{
            System.out.println("Auth Fail");
            res.cause().printStackTrace();
            ctx.fail(401);
        }
    });

This will able to return only the AccessToken with no refresh_token. So even I try to pass the refresh_token from my POST request body, it be meaningless to this.

**Comment by pmlopes** [comment]
2 things here, we need to link user to session objects and invalidate them at the same time.

**Comment by RaiBnod** [comment]
If we are using token-based authentication system, we want to log out from token also. I am using Keycloak API for doing log out for now as:

    private void redirectLogout(RoutingContext ctx) {
        JsonObject body = ctx.getBodyAsJson();
        User user = ctx.user();
        String access_token = user.principal().getString("access_token");
        String refresh_token = body.getString("refresh_token");
        JsonObject keycloakConfig = config().getJsonObject("keycloak");
        String client_id = keycloakConfig.getString("resource");
        String client_secret = keycloakConfig
                .getJsonObject("credentials").getString("secret");
        String realmName = keycloakConfig.getString("realm");
        String uri = keycloakConfig.getString("auth-server-url")
                + "/realms/" + realmName + "/protocol/openid-connect/logout";

        HttpClient client = vertx.createHttpClient(new HttpClientOptions());

        HttpClientRequest request = client.requestAbs(HttpMethod.POST, uri, response -> {
            ctx.response().setStatusCode(response.statusCode()).end();
        });
        request.setChunked(true);

        String body$ = "refresh_token=" + refresh_token + "&client_id=" + client_id
                + "&client_secret=" + client_secret;
        request.putHeader("content-type", "application/x-www-form-urlencoded");
        request.putHeader("Authorization", "Bearer " + access_token);

        request.write(body$).end();
    }

**Comment by pmlopes** [comment]
The user object as returned from the OAuth2 module already knows how to handle `logout` requests, however there are a couple of issues here:

1. logout per Keycloak requires a refresh token to be passed to the call
2. keycloak does not implement the token invalidation endpoint

So when the token is stored completely on the session, the session will include the refresh token and id token as returned from keycloak during the authentication process.

However when the token is just extracted from a request from the `Authorization` header in that case we only have access to the `access_token` which is not enough to perform the `logout` operation. From the `Auth` module perspective there is nothing we can do, from the `vertx-web` we need to verify if using a session we're restoring the right value (the full response) from keycloak or just using the token from the header.

Regardless, if no sessions are in place and the token was not acquired from the vertx application using the CODE flow, you won't be able to logout.

In order to work with token invalidation and if you're interested you can try to vote on Keycloak JIRA issue in order for them to implement it.

https://issues.jboss.org/browse/KEYCLOAK-5325

**Comment by pmlopes** [comment]
As this is a limitation of keycloak I'm closing the issue, feel free to re-open if there is more information
