### ISSUE TITLE
AuthInfo should be a DataObject

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#234]
Currently the `authInfo` data passed to the providers is a plain Json object, this can cause typpo bugs or have undocumented fields.

see: https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-common/src/main/java/io/vertx/ext/auth/AuthProvider.java

The goal would be to replace the JSON object with a DataObject that would allows static typing and validation.

**Comment by rgmz** [comment]
I'll create a POC for this.

Three thoughts:
1. This would require a breaking change (`authenticate(authInfo: JsonObject...)` and `authenticate(authInfo: DataObject...)` would be ambigious). Presumably why this was changed to 4.0?
2. Is there a complete list of documented fields available for reference?
3. Implementing https://github.com/vert-x3/vertx-codegen/pull/211 would make handling the DataObjects for modules that don't use camelCase (e.g. JWT) less painful. :stuck_out_tongue:

**Comment by rgmz** [comment]
@pmlopes Here's a rudimentary implementation of AuthInfo as a DataObject: https://github.com/rgmz/vertx-auth/commit/093c98f414606f69266b457fefc0e616c57a3070

Missing additional tests and a few inner classes are still being passed JsonObject from the initial AuthInfo (namely [`OAuth2TokenImpl`](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2TokenImpl.java)). Just wondering if you think this is a worthwhile approach.

(Annoyingly, the base `AuthInfo` cannot be an interface or abstract class since those are not recognized as valid parameters.)

**Comment by pmlopes** [comment]
@rgmz this looks great. As you can observe there's a code smell with oauth, the user info is used to configure the flows, probably that should have its own data object.

**Comment by pmlopes** [comment]
Fixed by #399 and #400
