### ISSUE TITLE
Broken Base64 OAuth2 AccessToken in KeycloakHelper

### ISSUE THREAD

**Issue by MetalMiner** [eclipse-vertx/vertx-auth#258]
### Version

* vert.x core: <= 4.6.2
* vert.x auth: <= 4.6.2

### Context

KeycloakHelper method `static JsonObject parseToken(String token)` converts like:
```
String decoded = new String(Base64.getDecoder().decode(parts[1]). "UTF-8");
```
The method `Base64.getDecoder().decode(parts[1])` looks like:
```
decode(src.getBytes(StandardCharsets.ISO_8859_1));
```
The codecs are **different**. This does work for most characters since the encodings have pretty much in common, but fails in special cases.

### Extra
You could use ```Base64.getUrlDecoder().(parts[1])``` as this does not change the decoding.

**Comment by michaelhunziker** [comment]
We are experiencing the same issues. As soon as a token contains a username with a special character e.g. "Joël" (containing special character UTF-8 HEX "c3 ab") we get the following error messages:

> java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.vertx.ext.auth.oauth2.KeycloakHelper.parseToken(KeycloakHelper.java:129)
	at io.vertx.reactivex.ext.auth.oauth2.KeycloakHelper.parseToken(KeycloakHelper.java:157)

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-auth/commit/31d5e5a0f834f174ea121e604cbafeec2fa4fe6b

Please note that this class has been marked for deprecation on 4.0. The reason is that it does not enforce a secure decode, so all information should be attained directly from the user principal object instead.

In the user the codec is correct (according to the spec) and here is wasn't.
