### ISSUE TITLE
OAuth2AuthHandlerImpl security is weak

### ISSUE THREAD

**Issue by MightyEagle82** [eclipse-vertx/vertx-auth#260]
### Version

* vert.x core: 3.6.3
* vert.x auth: 3.6.3

### Context

I encountered that **OAuth2AuthHandlerImpl** only checks if token is expired. It even does not check if user is really exists on authentication server. For example, I can easily get token from another authentication server to get access to my services. **OAuth2AuthHandlerImpl** interacts with authentication server only when user is tryed to be authorized.

I was wondered when saw **OAuth2AuthProviderImpl** class **authenticate** method which is used by **OAuth2AuthHandlerImpl** class.
For example, what does this comment mean:
```
// this validation can be done in 2 different ways:
// 1) the token is a JWT and in this case if the provider is OpenId Compliant the token can be verified locally
// 2) the token is an opaque string and we need to introspect it
```

Why is token not introspected by **OAuth2AuthHandlerImpl** for every HTTP request?!

**Comment by MightyEagle82** [comment]
Can anybody answer me?

**Comment by pmlopes** [comment]
Hi @artyomsafronov sorry for the delay, the trade off is validating tokens if in JWT format instead of always introspect was to avoid overloading the OAuth2 server.

Perhaps we should make this check optional and disabled by default. So if a user is willing to trust the tokens the flip the flag to do local checks, otherwise always delegate to the server.

The mode where we locally check tokens is valid for cases where we're doing machine to machine messaging and tokens are short lived for example.
