### ISSUE TITLE
OAuth2TokenImpl scope's value is List causing ClassCastException

### ISSUE THREAD

**Issue by lizhongyue248** [eclipse-vertx/vertx-auth#289]
### Version

* vert.x core:3.8.0
* vert.x auth:3.8.0

### Context

Hi, in our oauth authorization server, the `scope` is List. We build authorization server by spring-security-oauth2. This is his default implementation.

In vert.x Oauth, use `authenticate` and `introspectToken` method, I will get a ClassCastException. I find this question in the source code.

[source](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2TokenImpl.java#L389)

```
if (json.containsKey("scope") && json.getString("scope") != null) {
      // A JSON string containing a space-separated list of scopes associated with this token
      principal().put("scope", json.getString("scope"));
}
```

This exception occurs at `json.getString("scope")`. But my scope is 

```
    "scope": [
        "read", "write"
    ],
```

Why not use this?

```
if (json.containsKey("scope") && json.getValue("scope") != null) {
      principal().put("scope", json.getValue("scope"));
}
```

This way can adapt to all types

Thanks!

**Comment by lusoalex** [comment]
Hi @lizhongyue248, I was searching some official documentation, but the only one I found is the token introspection [here](https://tools.ietf.org/html/rfc7662#section-2.2) which define scope as a string containing space-seperated list of scopes.

So I am wondering if the fix should be done on the spring security side, what's your opinion?

By the way, I am looking how to handle the scope currently, I guess it is not in the JWTOptions attributes because it is not specified into the [JWT specification](https://tools.ietf.org/html/rfc7662#section-2.2) claims.

**Comment by pmlopes** [comment]
We can try to add an exception for the scope array. Scopes are not a jwt feature, they are an oauth2, so they are handled there.
