### ISSUE TITLE
simple oauth2 server side support

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#39]
For 3.2 we would like to have some simple oauth2 support, the MVP is to support authentication using a third party such as Github/Facebook/Google

**Comment by millross** [comment]
Started on this here: https://github.com/millross/vertx-web-oauth2 (non-blocking) - feel free to take it over

I'm also working on vertx-pac4j which should be released pretty soon, but that has blocking calls (wrapped in executeBlocking) so isn't non-blocking end to end (because underlying pac4j libs contain blocking calls).

**Comment by aniketkulkarni2013** [comment]
Is it possible to setup OAuth 2 Authorization server with vert.x 3.3.0 ?

**Comment by millross** [comment]
Not as far as I know, assuming you mean a provider rather than a server which uses an external OAuth 2 provider for authentication.
