### ISSUE TITLE
Documentation uses deprecated classes and methods for the JWT Auth Provider.

### ISSUE THREAD

**Issue by gaberust** [eclipse-vertx/vertx-auth#438]
The JWT Auth documentation makes use of several deprecated classes and methods, including:
```
KeyStoreOptions (the entire class is deprecated)
PubSecKeyOptions::setPublicKey
PubSecKeyOptions::setSymmetric
```

There are no details on many of the class methods (literally just the name of the method, parameter types, and return type) in the API docs, and no indication or recommendations anywhere about what methods should be used instead. The mentioned documentation can be viewed at:

[https://vertx.io/docs/vertx-auth-jwt/java/](https://vertx.io/docs/vertx-auth-jwt/java/) 

[https://vertx.io/docs/vertx-web/java/#_jwt_authorisation](https://vertx.io/docs/vertx-web/java/#_jwt_authorisation)

**Comment by gaberust** [comment]
After reviewing some source code, I discovered that recommended method calls and reason for deprecation are documented in the comments. However, the documentation on vertx.io is still out of date, and none of it appears in the JavaDoc.

**Comment by pmlopes** [comment]
Hi @gaberust the original plan was to deprecate `KeystoreOptions` as it was not handling many use cases and it's internal were buggy. In turned out (see the current 4.0.0 candidate releases) that it was possible to fix the behaviour without breaking the existing API so in 4 you will see that the class is still there. Not all API is deprecated, but just some of the methods.

For `PubSecKeyOptions` some javadocs have already been added but you're right not all of them are explaining the reason why.

**Comment by gaberust** [comment]
So the plan is to fix the internal implementation instead of deprecating it indefinitely? That works as well.

**Comment by gaberust** [comment]
Closed issue, as documentation is updated with non-deprecated methods in current stable.
