### ISSUE TITLE
WildcardPermissionBasedAuthorization behaves unexpected in combination with PermissionBasedAuthorization

### ISSUE THREAD

**Issue by synth3** [eclipse-vertx/vertx-auth#477]
### Version

4.0.3

### Summary

`WildcardPermissionBasedAuthorization` seems to only work (respecting wildcards at verification) in combination with other instances of `WildcardPermissionBasedAuthorization`. As I expected them to also work with `PermissionBasedAuthorization` and I was not able to find documentation regarding that topic I'm creating this issue. ...My expectation may be wrong.

### How to reproduce

```java
System.out.println(
    WildcardPermissionBasedAuthorization.create("*")
         .verify(PermissionBasedAuthorization.create("test"))); // outputs 'false'
```

I would have expected that the output is `true`.

**Comment by pmlopes** [comment]
@stephanebastian can you comment here?

**Comment by stephanebastian** [comment]
Hey @pmlopes and @synth3,
It indeed looks like a bug to me. 
I quickly looked at the code and believe that the problem lies at line 85 of https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-common/src/main/java/io/vertx/ext/auth/authorization/impl/WildcardPermissionBasedAuthorizationImpl.java. 
It problably should be something along the lines:
`
if (wildcardPermission.implies(otherPermission.getPermission()) {
`
We can probably solve this issue by adding a new method -> WildcardExpression.implies(String value)
I'll post a fix by the end of the day.
