### ISSUE TITLE
Documentation incorrect for token call based on authcode

### ISSUE THREAD

**Issue by narras-oss** [eclipse-vertx/vertx-auth#519]
### Questions

I followed the documentation on https://vertx.io/docs/vertx-auth-oauth2/java/

and set redirect_uri, along with 'code' in the JsonObject passed into authenticate. However i didn't see redirect_uri sent in the request. Source code shows "redirectUri" is the name of the parameter. Please fix docs

oauth2.authenticate(
  new JsonObject()
    .put("code", code)
    .put("redirect_uri", "http://localhost:8080/callback"))
  .onSuccess(user -> {
    // save the token and continue...
  })
  .onFailure(err -> {
    // error, the code provided is not valid
  });
### Version

Latest docs

### Context

When upgrading from 3.9.9 to 4.2.1, I followed the documentation to make the changes. This parameter name did not seem to change but it caused regression and upon debugging found this issue. After i changed the attribute name from "redirect_uri" to "redirectUri" in the input JsonObject, it worked.

### Do you have a reproducer?

N/A

### Steps to reproduce

N/A

**Comment by The-Toast-aka-Pablo** [comment]
I second that and thanks for the workaround! This bug is really confusing, especially since the naming is otherwise still `redirect_uri`.

**Comment by pendula95** [comment]
This fixed the issue in documentation for token call but the changes also affected the initial authorizeURL to which user should be sent to. In this case generated authorizeURL will have parameter redirectUri which is not correct and instead should be redirect_uri.

This can be fixed by completing #542 and adding additional code in  authorizeURL implementation to map correct fields
