### ISSUE TITLE
JWT Signature verification failed with multithread

### ISSUE THREAD

**Issue by lxitgto** [eclipse-vertx/vertx-auth#54]
sometimes JWT.decode will throw the RuntimeException("Signature verification failed") when we use blockingHandler or generateToken/authenticate in different thread.

I think it's because CryptoMac use mac.doFinal to generate digests and it's not [thread-safe.](http://stackoverflow.com/questions/31898802/is-macdofinal-thread-safe-in-java)

**Comment by davidafsilva** [comment]
Yeah, you cannot reuse instances of the same `Mac` instance without proper synchronization, since its internal state is changed during MAC computation and finally to reset back to the last `init()` known state (hence you can reuse the same instance with the same key without calling `init()`).

The above (with slightly different implementation related details) is also applicable to `Signature`, which is used by `CryptoSignature`.
