### ISSUE TITLE
Keycloak handler fails on reload

### ISSUE THREAD

**Issue by paulbakker** [eclipse-vertx/vertx-auth#64]
### Version
- vert.x core: master (May 1st)
- vert.x auth: master (May 1st)
### Context

I created a Keycloak handler as shown in this [video](http://vertx.io/blog/vertx-3-and-keycloak-tutorial/).

```
Vertx vertx = Vertx.vertx();        
Router router = Router.router(vertx);
OAuth2AuthHandler oauth2 = OAuth2AuthHandler.create(OAuth2Auth.createKeycloak(vertx, OAuth2FlowType.AUTH_CODE, new JsonObject("...")), "http://localhost:8282");
oauth2.setupCallback(router.get("/callback"));
router.route("/secure/*").handler(oauth2);
router.route("/secure/test").handler(rc -> {
    rc.response().end("This is a secure page!");
});

vertx.createHttpServer().requestHandler(router::accept).listen(8282);
```

The request to `secure/test` gets redirected to the Keycloak login page as expected. After login I get redirected like `url http://localhost:8282/callback?redirect_uri=/secure/test&state=&code=mYYbNf79vby_ALu5M2swWwJ0Com4eto5RQNJpPjjduQ.b09a7d59-ef84-4dd1-a981-b16a396fed16`, which shows `This is a secure page!` correctly.
When I refresh the page however, it fails. The page returns "Internal Server Error", and on the application's console I see:

```
io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
io.vertx.core.impl.NoStackTraceThrowable: Bad Request
```

**Comment by paulbakker** [comment]
It seems that every request that follows the original request that actually got redirect to the login page fails.

**Comment by pmlopes** [comment]
maybe related to #65

**Comment by pmlopes** [comment]
The redirect URL can only be used once, it is part of the OAuth2 handshake, it contains a code that needs to be sent back to the OAuth2 server to verify that you requested to be authenticated. If you reload this page, the OAuth2 server will deny you a new token since the code is not valid anymore so you will get a bad request.

What is missing here is that once you authenticate and land on the secure page, you should create a session to store the user say using a cookie for example and force the browser to redirect to a protected resource this way the callback url is removed from your current href location and reloads will work since they will not ask for a new token anymore but be validated by the session handler.

**Comment by paulbakker** [comment]
Makes sense. I do think it needs to be in the docs/tutorial though, it's not directly obvious that this isn't handled automatically.

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-web/commit/cbfcb9713fed9cb6658aadedf210096c1db124ff
