### ISSUE TITLE
Shiro's BasicAuthentication doesn't detect deleted key-value on reload

### ISSUE THREAD

**Issue by dangnhdev** [eclipse-vertx/vertx-auth#74]
### Version
- vert.x core: 3.3.0
- vert.x auth: 3.3.0
### Context

I written some code to perform Basic Authentication with Vertx ShiroAuth.

``` java
        JsonObject authConfigObject = new JsonObject();
        authConfigObject.put(
                PropertiesProviderConstants.PROPERTIES_PROPS_PATH_FIELD,
                new File(appConfig.getUserPropertiesPath()).toURI().toString() /*to let shiro auto reload properties file */
        );

        ShiroAuthOptions shiroAuthOptions = new ShiroAuthOptions();
        shiroAuthOptions.setType(ShiroAuthRealmType.PROPERTIES);
        shiroAuthOptions.setConfig(authConfigObject);
```

Example properties file:

```
user.admin=12345678
user.staff=123
```

If I add new key-value to properties file, Shiro can detect and reload perfectly. But when I delete, shiro reload (the debug log said that) but nothing change (user can still login by using those deleted key-value).

**Comment by pmlopes** [comment]
are you using sessions? if you do you must invalidate the session too otherwise it will be assumed that the user is still valid until the session expires. Also note that internally we don't keep any info on the users so it is all delegated to shiro. If the problem is not session related could you provide a full reproducer since just with the config we're not able to reproduce your bug.

**Comment by pmlopes** [comment]
No feedback for more than 1 year, will close.
